package referenzixx.ui;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicListUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jbibtex.BibTeXEntry;
import org.jbibtex.Key;
import referenzixx.database.DatabaseUtils;

/**
 *
 * @author Johannes
 */
public class MainUI extends javax.swing.JFrame {

    private DatabaseUtils dbutils;
    private String filters;

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        this.dbutils = new DatabaseUtils();
        this.filters = "";

        initComponents();
        initListeners();
        refresh();
    }

    public MainUI(DatabaseUtils dbutils) {
        this.dbutils = dbutils;
        this.filters = "";

        initComponents();
        initListeners();
        refresh();
    }

    public DatabaseUtils getDBUtils() {
        return this.dbutils;
    }

    /**
     * Refreshes the reference table to match the list in DatabaseUtils.
     */
    public final void refresh() {
        List<BibTeXEntry> references;
        if (filters.isEmpty()) {
            references = dbutils.getReferences();
        } else {
            references = dbutils.getReferences(filters);
        }

        DefaultTableModel tableModel = (DefaultTableModel) referenceTable.getModel();
        tableModel.setRowCount(0); // Clear the table
        tableModel.setRowCount(references.size());

        int row = 0;
        for (BibTeXEntry reference : references) {
            displayReference(reference, row++);
        }
    }

    private void displayReference(BibTeXEntry entry, int row) {
        TableModel tableModel = referenceTable.getModel();
        tableModel.setValueAt(entry.getKey().toString(), row, 0);
        tableModel.setValueAt(entry.getField(new Key("author")).toUserString(), row, 1);
        tableModel.setValueAt(entry.getField(new Key("title")).toUserString(), row, 2);
        tableModel.setValueAt(entry.getField(new Key("year")).toUserString(), row, 3);
    }

    private void refreshFilters() {
        this.filters = searchField.getText();

        refresh();
    }

    private void initListeners() {
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                refreshFilters();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                refreshFilters();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                refreshFilters();
            }
        };

        searchField.getDocument().addDocumentListener(documentListener);
        
        ListSelectionModel listSelectionModel = referenceTable.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        listSelectionModel.addListSelectionListener((ListSelectionEvent e) -> {
            if (referenceTable.getSelectedRow() == -1) {
                delReferenceButton.setEnabled(false);
            }
            else {
                delReferenceButton.setEnabled(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addReferenceButton = new javax.swing.JButton();
        copyButton = new javax.swing.JButton();
        readButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        referenceTable = new javax.swing.JTable();
        delReferenceButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        addReferenceButton.setText("Lisää");
        addReferenceButton.setToolTipText("Lisää uusi artikkeli");
        addReferenceButton.setName("addButton"); // NOI18N
        addReferenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReferenceButtonActionPerformed(evt);
            }
        });

        copyButton.setText("Kopioi leikepöydälle");
        copyButton.setToolTipText("Kopioi BibTex-tiedoston leikepöydälle");
        copyButton.setName("copyButton"); // NOI18N
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        readButton.setText("Valitse tiedosto");
        readButton.setName("selectButton"); // NOI18N
        readButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonActionPerformed(evt);
            }
        });

        referenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", "", ""},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Viite", "Kirjoittaja", "Otsikko", "Vuosi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(referenceTable);

        delReferenceButton.setText("Poista");
        delReferenceButton.setEnabled(false);
        delReferenceButton.setName("delButton"); // NOI18N
        delReferenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delReferenceButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Hae viitteitä");

        searchField.setToolTipText("");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addReferenceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delReferenceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(readButton)
                        .addGap(18, 18, 18)
                        .addComponent(copyButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(copyButton)
                        .addComponent(readButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addReferenceButton)
                        .addComponent(delReferenceButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        dbutils.copyToClipboard();
    }//GEN-LAST:event_copyButtonActionPerformed

    private void addReferenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReferenceButtonActionPerformed
        new NewReferenceDialog(this, true).setVisible(true);
    }//GEN-LAST:event_addReferenceButtonActionPerformed

    private void readButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            dbutils.selectFile(chooser.getSelectedFile());
            refresh();
        }
    }//GEN-LAST:event_readButtonActionPerformed

    private void delReferenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delReferenceButtonActionPerformed
        List<BibTeXEntry> references = dbutils.getReferences();
        int selectedRow = referenceTable.getSelectedRow();
        if (selectedRow != -1) {
            dbutils.delEntry(references.get(selectedRow));
        }
        
        refresh();
    }//GEN-LAST:event_delReferenceButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        System.out.println("asdf");
        refreshFilters();
    }//GEN-LAST:event_searchFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReferenceButton;
    private javax.swing.JButton copyButton;
    private javax.swing.JButton delReferenceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton readButton;
    private javax.swing.JTable referenceTable;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
